### ISSUE TITLE
Resuming a game app will sometimes not work

### ISSUE THREAD

**Issue by ceedveed** [Merrit/nyrna#51] opened 2021-08-25 21:48 UTC
**Describe the bug**
Resuming a game app will not work correctly all the time. But I cannot identify a specific pattern or cause. This only uncommonly happens (maybe once every 20 suspend/resumes?). Not sure. Only clue I have is the log.

**To Reproduce**
1. Suspend app in Nyrna
2. Resume app in Nyrna
3. Status of app stays "orange" (suspended) despite several clicks. I've also tried manually refreshing by turning off auto refresh.
4. Open Resource Monitor of Windows 10.
5. Resume then suspend app in Resource Monitor.
6. Go back to Nyrna and resume app.
7. Now app is resumed correctly.

**Expected behavior**
Expect app to resume without using Resource Monitor.

**Screenshots**

**Software (please complete the following information):**
 - OS: Windows 10 20H2, Nyrna v2.2.0

**Additional context**
LOG files (ALL):

2021-08-25 11:40:04.944296 
WARNING 
Logger: Win32Process 
Error getting executable name: 6 

--------
EDIT: okay as soon as it happened again I took a look at the log:

2021-08-26 23:03:19.939150 
WARNING 
Logger: Win32Process 
Error getting executable name: 6 

I think this executable name error is causing this.

**Comment by Merrit** [comment] 2021-10-30 21:20
When this happens, if you restart Nyrna does resuming the app work properly?

**Comment by Merrit** [comment] 2021-12-03 21:42
When this happens, if you restart Nyrna does resuming the app work properly?

**Comment by mrrfv** [comment] 2022-01-02 20:52
Please re-open this issue - I have the exact same issue on Windows 10. It seems to happen after suspending the system (i.e. closing the lid) and when the app hasn't been resumed for a few hours.

I just force-closed the game that didn't want to resume (and lost all my progress), but I'll make sure to make screenshots and try to restart Nyrna if it happens again.

**Comment by Merrit** [comment] 2022-01-03 16:06
@mrrfv Yes, restarting Nyrna would be good. If that fails then also please try running Nyrna as admin and see if that has any effect.

I'll look into the possibility of adding additional logging for the issue. :+1:

**Comment by mrrfv** [comment] 2022-01-19 14:25
@Merrit Managed to reproduce this issue on Windows for 3 apps (Paint, Minecraft launcher, Minecraft). It's as simple as suspending an app and closing the laptop lid (putting it to sleep). Upon opening the lid, Windows will say the app is 'not responding' and Nyrna won't be able to resume it. If Nyrna is restarted, it thinks that the suspended app is resumed.

**Comment by Merrit** [comment] 2022-01-19 18:38
@mrrfv Thanks for the info, I think I can now reproduce this issue. I will see if I can do some debugging on it :)

**Comment by Merrit** [comment] 2022-01-25 23:12
@ceedveed @mrrfv I think I may have resolved the issue, would you be willing to test the new build?

[Nyrna-Windows-Installer.zip](https://github.com/Merrit/nyrna/files/7937829/Nyrna-Windows-Installer.zip)
[Nyrna-Windows-Portable.zip](https://github.com/Merrit/nyrna/files/7937830/Nyrna-Windows-Portable.zip)

**Comment by mrrfv** [comment] 2022-01-26 17:28
I suspended 3 apps (Discord, Brave mid-sleep, Spotify) on the new Portable build, closed and opened my laptop's lid and Nyrna went crazy - Brave was correctly reported as suspended, but other apps weren't. When I tried to resume Spotify, Nyrna crashed. I don't know what happened there...

![image](https://user-images.githubusercontent.com/92185687/151213818-d5ff4850-ccec-4a6b-885e-995c4c962a96.png)

---

After restarting Nyrna, it correctly resumes all the apps, so I suppose the issue is somewhere in auto refresh.

**Comment by mrrfv** [comment] 2022-01-26 17:34
I tried to resume 2 apps at once and it showed a PowerShell error (which I think is related to Nyrna, as it uses that under the hood).

![image](https://user-images.githubusercontent.com/92185687/151215972-be2446e2-4c35-42eb-9368-554247aa49d9.png)

**Comment by Merrit** [comment] 2022-01-26 17:39
Wow, that's something.

Are you able to trigger the issue in any way besides suspending your computer?

**Comment by mrrfv** [comment] 2022-01-26 18:06
Not sure to be honest.

**Comment by Merrit** [comment] 2022-01-31 19:51
I presume that Nyrna being suspended itself when you suspend the computer causes its refresh timer to break.

This kind of issue is definitely why we have a disclaimer that funny things can happen when suspending a process.. I don't think there is really a way to check for and recover from such an issue. I'd suggest if you are suspending the entire computer to either switch Nyrna to manual refresh, or to close it before suspending the computer.

I have definitely cleaned up the code where we update the status of a process, and it is much more reliable now and that specific bug appears to be resolved. Thanks for all the help with troubleshooting and figuring out this issue! :tada:

**Closed** 2022-01-31 20:23 UTC
Labels: bug
