### ISSUE TITLE
[BUG] Steam thinks game is still running when suspended

### ISSUE THREAD

**Issue by EliasGagnef** [Merrit/nyrna#22] opened 2020-11-22 20:52 UTC
When suspending a game Steam still thinks it is running and therefore logs hours played, I am unsure if this is possible to fix, if it isn't please close this issue.

**Comment by Merrit** [comment] 2020-11-22 22:34
Hey, thanks for the report!

Unfortunately this is not possible to fix.

Steam watches the process of the game, and says "Yep, it is still alive." Doesn't care if it is suspended or not. The only point at which it stops tracking the time played is when that process ends (which closes the game).

I'd love if someone proved me wrong, because this one annoys me as well. Until then I'll close this issue, but again thanks for contributing :)

**Closed by Merrit** 2020-11-22 22:34 UTC

**Comment by JpTiger** [comment] 2023-07-09 21:24
Since this is gaming we're talking about, I'm guessing there's a good chance most users will also suspend their system. Regular sleep mode won't help with this, but what about hibernation?

**Comment by Merrit** [comment] 2023-07-11 16:11
> what about hibernation?

I would expect using the sleep or hibernate feature could cause unexpected behaviour, maybe crashes. It would definitely vary depending on the game.

One thing that could be done regarding Steam's time played is to send feedback to Valve, ask them if the timer can account for whether the process is actually running or not instead of just alive. I sort of doubt they'd make such a change, because it would require more work to keep checking the status of the process but you could ask. :smile:
