### ISSUE TITLE
Version 2.5.0 does not start hotkey automatically at system startup.

### ISSUE THREAD

**Issue by jjw410** [Merrit/nyrna#92] opened 2022-08-11 14:36 UTC
Unfortunately even with the option toggled to launch at system startup nothing happens on a fresh boot. This is also after using Revo Uninstaller to clean every part of old Nyrna builds off of the system.

Functionality is thankfully normal when the app is started manually, however.

**Comment by Merrit** [comment] 2022-08-11 18:19
Hi @jjw410 :wave: 

Thanks for the report! I can see what the issue is, I will fix it shortly when I get a chance. :smiley:

**Comment by jjw410** [comment] 2022-08-11 20:49
Thanks so much, Kristen! Much appreciated! 😄

**Comment by Merrit** [comment] 2022-08-13 21:42
Should be resolved with #93 and available with release [2.5.1](https://github.com/Merrit/nyrna/releases/tag/v2.5.1). :+1: 

Feel free to reopen if there is still an issue. Thanks again for the report! :sunflower:

**Closed by Merrit** 2022-08-13 21:42 UTC
Labels: bug

**Comment by jjw410** [comment] 2022-08-13 23:42
Amazing work -- thank you K! 😄
