### ISSUE TITLE
Does not work with Flatpak'd apps

### ISSUE THREAD

**Issue by jntesteves** [Merrit/nyrna#13] opened 2020-08-27 02:12 UTC
The tool does not work with Flatpak'd apps. The notification is shown saying the app was suspended, but the app is not actually suspended. Pressing the hotkey again does not trigger the resumed notification. Pressing the key a third shows the suspended notification again.

I'm not sure if any process is actually being suspended. Monitoring all processes using Gnome's System Monitor does not list any process with a status of Stopped.

I haven't tried yet if games started by the Flatpak version of Steam work, since I reverted to using Steam installed on the system due to other issues.

Tested on  Fedora 32 - GNOME 3.36

**Comment by Merrit** [comment] 2020-08-27 15:03
I can confirm this, Flatpak apps seems to be getting reported as PID 0.

Thanks for the report! Will investigate.

**Comment by jntesteves** [comment] 2020-08-28 15:25
An update, I know it's expected but I tested Flatpak'd Steam and confirm that processes started by Steam also can not be targeted, so I guess anything running inside the container is invisible to the tool as it currently is.

**Comment by Merrit** [comment] 2020-09-15 19:33
I have been trying to investigate this issue.

It seems that the inside of a Flatpak has its own namespace, and the PID of the outside application we "see" is completely seperate from what is inside the container. https://github.com/flatpak/flatpak/issues/1523

I had thought maybe we could take the name of the window, search for a running Flatpak instance of the same, enter it and search for the PID we need to suspend, etc..

However even if this is possible, given that the app can choose to display any arbitrary name it likes, I am not sure how we would resolve this. For example, `Flatseal` changes its displayed name depending on which app you are managing, so if I am managing the permissions for `Plex Media Player` it reports *itself* as `Plex Media Player`.

Given that Flatpak itself seemed to deem this unresolveable 2 years ago, I am currently unsure how to proceed re:Flatpak support.

**Comment by Merrit** [comment] 2021-02-22 18:40
Given that Flatpak has shown no progress towards this and I haven't seen a reasonable workaround, I am going to sadly close this issue now as wontfix. Hopefully Flatpak will fix this on their end at some point.

**Closed by Merrit** 2021-02-22 18:40 UTC
Labels: wontfix
