### ISSUE TITLE
Scrollbar in settings doesn't work

### ISSUE THREAD

**Issue by BlueManCZ** [Merrit/nyrna#94] opened 2022-08-14 09:05 UTC
Moving the scrollbar by dragging it with a mouse cursor is impossible. The window can be scrolled with the mouse wheel.

![obrazek](https://user-images.githubusercontent.com/17854950/184529923-5e926305-b0c5-4b23-ba1e-041d0e02d2c6.png)

**Comment by Merrit** [comment] 2022-08-15 15:16
Thanks for the report!

I can confirm the issue. Only seems to happen in the release build, works fine in debug so I'll have to investigate. :smiley:

**Comment by Merrit** [comment] 2022-08-16 19:58
Turns out the CI system was still building from Flutter beta - works fine from Stable! Should be resolved with d817485d701653c75662e4cfc5577842c4897ac0 and available in [v2.5.2](https://github.com/Merrit/nyrna/releases/tag/v2.5.2)

If you still find a problem feel free to reopen the issue.
Thanks again for the report! :tada:

**Closed by Merrit** 2022-08-16 19:58 UTC
