### ISSUE TITLE
Freezing game without using the hotkey

### ISSUE THREAD

**Issue by darkguset** [Merrit/nyrna#210] opened 2024-04-01 09:42 UTC
I am not 100% sure Nyrna is at fault - but so far when I run the game (Everspace) without Nyrna running in the background I have no issues at all. If Nyrna is active, then the game will seem to play fine for a while then at some point it will freeze (perhaps related to audio?). When the game freezes, sometimes Nyrna will allow me to go to desktop (use hotkey) and then freeze itself (it will not return to game) and sometimes the hotkey doesn't work at all.

This is with the latest version 2.19.0? Using the previous version(s) I didn't experience this issue.

Operating System: Linux Mint 21.3                 
Kernel: Linux 6.5.0-26-generic
Architecture: x86-64

**Comment by Merrit** [comment] 2024-04-01 18:57
Please try running Nyrna from CLI, reproduce the issue, and paste the output here.

Eg. run from a terminal:

```bash
nyrna
```

or for Flatpak:

```bash
flatpk run codes.merritt.Nyrna
```

**Comment by darkguset** [comment] 2024-04-04 13:31
I played quite a bit today - I even used Nyrna to Desktop and back without any crashing. Yesterday there was an update on the NVIDIA drivers which I did - perhaps that was it.Anyway, I did what you said and here are some messages from the terminal - not sure if this helps at all (related to any issues or not).

Gtk-Message: 22:05:53.099: Failed to load module "xapp-gtk3-module"
(nyrna:2): Gdk-CRITICAL **: 22:05:54.403: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failedflutter:   ERROR ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────flutter:   ERROR │ #0   flatpakRun.<anonymous closure> (package:nyrna/native_platform/src/linux/flatpak.dart:21)flutter:   ERROR │ #1   <asynchronous suspension>flutter:   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄flutter:   ERROR │ ⛔ Issue running command through flatpak-spawn: xdotool: Unknown command: getactivewindow getwindownameflutter:   ERROR │ ⛔ Run 'xdotool help' if you want a command listflutter:   ERROR └──────────────────────────────────────────────────────
    On Tuesday, 2 April 2024 at 05:58:15 GMT+11, Kristen McWilliam ***@***.***> wrote:  
 
 


Please try running Nyrna from CLI, reproduce the issue, and paste the output here.

Eg. run from a terminal:
nyrna
or for Flatpak:
flatpk run codes.merritt.Nyrna

**Comment by Merrit** [comment] 2024-04-05 18:20
I'm glad its been working!

Nothing notable in this output, but since it ran fine that seems expected.

I'll close this for now, but if it happens again feel free to reopen the issue! :)

**Closed by Merrit** 2024-04-05 18:20 UTC
