### ISSUE TITLE
Deathloop (epic launcher) freezes/crashes when suspending

### ISSUE THREAD

**Issue by Lestat79be** [Merrit/nyrna#97] opened 2022-08-16 21:13 UTC
When I try to suspend the game Deathloop, the spinner of the nyrna application freezes and the deathloop process gets suspended, but is non responsive. The green circle does not turn orange, and I cannot click the item again in nyrna. I then have to kill the deathloop process after witch nyrna app shows an error.
I'm using the Epic game launcher, and I know Deathloop uses Denuvo DRM.

**Comment by Merrit** [comment] 2022-08-17 15:23
Is this on Windows?

What is the error that Nyrna shows?

The game being unresponsive is expected, all apps become unresponsive when suspended. If you close/restart Nyrna, does it report the game as suspended? Can you resume then?

**Comment by Lestat79be** [comment] 2022-08-17 16:36
Yes, this is on windows.
When trying to suspend, nyrna animation freezes, game seems suspended, but i cannot unsuspend using nyrna
![2022-08-17 18_30_19-Nyrna](https://user-images.githubusercontent.com/111393391/185193896-e72900de-e1ae-4825-88d0-e6c2839107b5.png)

After closing and restarting nyrna, i see the process in nyrna as running, but the game is still suspended
![2022-08-17 18_30_42-Nyrna](https://user-images.githubusercontent.com/111393391/185194201-02a9be06-7383-43e4-8493-a6cde8600884.png)

The only thing I can do is kill the process using task manager. If I kill the process without restarting nyrna, I get a generic error message "interaction error" about easy anti cheat that could be the cause.

**Comment by Merrit** [comment] 2022-08-18 14:32
This seems to be caused by the game's use of Denuvo DRM. Denuvo's entire purpose is to prevent people from manipulating the game, and it seems to be working.

Unfortunately not much to be done about the issue - one of the many reasons I do not support games that use Denuvo.

I will close this issue since I can't do anything about their use of DRM.. if you feel it needs more attention, feel free to re-open it. :sunflower:

**Closed by Merrit** 2022-08-18 14:32 UTC
